services:
  sharelist-server:
    image: your-repo/sharelist21:latest
    container_name: sharelist-server
    restart: unless-stopped
    ports:
      - "5021:80"
    volumes:
      - ./data:/data
      # You can add multiple folders
      - ./media/movies:/media/movies
#     - ./tv:/media/tv
    environment:
      - ROLE=SERVER
      - APP_USERS=Joe,Lamar,Josh # Add/remove users here
      - APP_PIN=1234
      - HOST_USER=Joe  # Enables the server to self-scan /media
      - MEDIA_ROOT=/media