services:
  sharelist-server:
    image: volumedata21/sharelist21:latest
    container_name: sharelist-server
    restart: unless-stopped
    ports:
      - "5021:80"
    volumes:
      - ./data:/data
      - ./media/movies:/media/movies
    environment:
      - APP_USERS=Joe,Lamar,Josh # Must add all users here
      - APP_PIN=1234
      - SYNC_SECRET=REPLACEME # Same secret for everyone
      - HOST_USER=Joe
      # No MASTER_URL means "I am the Master"
      - MEDIA_ROOT=/media
      - CRON_SCHEDULE=0 3 * * * # Optional, auto sync at 3 AM
      - NODE_URL=http://hosts_server_URL.com:5021

# Generate a SYNC_SECRET using command line: 'openssl rand -hex 32'