services:
  sharelist-server:
    image: volumedata21/sharelist21:latest
    container_name: sharelist-server
    restart: unless-stopped
    ports:
      - "5021:80"
    volumes:
      - ./data:/data
      - /path/to/downloads:/downloads
      - /path/to/movies:/media/movies
      - /path/to/tvshows:/media/tvshows
      - /path/to/music:/media/music

    environment:
      - APP_USERS=Joe,Lamar,Josh # Must add all users here
      - APP_PIN=1234
      - SYNC_SECRET=REPLACEME # Same secret for everyone
      - HOST_USER=Joe
      - MEDIA_ROOT=/media
      - DOWNLOAD_ROOT=/downloads
      - CRON_SCHEDULE=0 3 * * * # Optional, auto sync at 3 AM
      - NODE_URL=https://yourdomain.com
        # CRITICAL: This must be your Public IP or Domain. 
        # Clients use this URL to connect to you.

# Generate a SYNC_SECRET using command line: 'openssl rand -hex 32'
# App pin can be any length and combination of numbers and letters.